### ISSUE TITLE
off-by-one-pixel问题

### ISSUE THREAD

**Issue by longfangsong** [tuxinghuan/overwatchLoading#1]
如图，差了一像素
<img width="294" alt="屏幕快照 2019-04-11 下午7 10 45" src="https://user-images.githubusercontent.com/13777628/55953049-ad59d300-5c8d-11e9-977a-f23b2719edfa.png">

浏览器：
Safari 12.1 (14607.1.40.1.4)

**Comment by longfangsong** [comment]
btw，我一直以为把这个传到Git上是一个段子
<img width="166" alt="屏幕快照 2019-04-11 下午7 13 11" src="https://user-images.githubusercontent.com/13777628/55953140-ea25ca00-5c8d-11e9-886e-3ef0f41913f6.png">

**Comment by tuxinghuan** [comment]
已修复（忘了加gitignore 😅
